/** @deprecated Import from @/lib/store instead */
export {
  addWorkOrder,
  addWorkOrdersBatch,
  deleteMitra,
  getAvailableWorkOrders,
  getFullState,
  getMitraByEmail,
  getMitraList,
  getMitraWorkOrders,
  getPayouts,
  getMitraPayouts,
  getProofs,
  getProofsByWo,
  getWorkOrderById,
  getWorkOrders,
  takeSlot,
  updateMitraStatus,
  updatePayoutStatus,
  updateSlotProgress,
  uploadProof,
  uploadTransferProof,
  verifyMitraLogin,
  verifySlot,
} from "@/lib/store";
